<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TVSecurityToolkit.Reporting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TVSecurityToolkit.Core\TVSecurityToolkit.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Templates\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
