<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TVSecurityToolkit.Tests.PayG</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TVSecurityToolkit.Core\TVSecurityToolkit.Core.csproj" />
    <ProjectReference Include="..\TVSecurityToolkit.Engine\TVSecurityToolkit.Engine.csproj" />
  </ItemGroup>
</Project>
